version: "3.8"
services:
  frontend:
    build: frontend
    container_name: frontend_c
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: always
  backend:
    build: .
    container_name: backend_server_container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/post"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: always
  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: always
